spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
  h2:
    console:
      enabled: true
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  token:
    secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ6.eyJzdWIiOiIiLCJuYW1lIjoiSm3obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt23Lno
    expire-length: 1800000
